from __future__ import annotations

import uuid
from dataclasses import dataclass

from pydantic import BaseModel, Field

from enterpriseagents.core.models import AcceptanceCriteria, Task
from enterpriseagents.llm.provider import LlmProvider


class Plan(BaseModel):
    """Represents the structured project plan generated by the Director agent."""
    tasks: list[Task]


@dataclass
class DirectorAgent:
    """Responsible for converting high-level instructions into executable plans.
    
    The Director Agent analyzes the user's request and decomposes it into a series of discrete, verifiable tasks. Each task is assigned specific acceptance criteria to ensure objective completion.
    """

    llm: LlmProvider
    name: str = "director"

    def plan(self, instruction: str) -> list[Task]:
        """Generates a task list based on the provided instruction.
        
        This method queries the language model to create a logical sequence of development tasks. It ensures that the output conforms to the Plan schema and assigns unique identifiers to each task before returning them.
        """
        
        system_prompt = (
            "You are a Senior Technical Project Manager.\n"
            "Break down the user's request into a small, logical sequence of development tasks.\n"
            "Each task must have concrete acceptance criteria (shell commands to verify it).\n"
            "Return a clean JSON list of tasks."
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Request: {instruction}"},
        ]

        # I'm asking the LLM for a structured 'Plan' object.
        # This guarantees I get a valid list of tasks, not random text.
        plan_obj = self.llm.structured(messages=messages, schema=Plan)
        
        # Ensure every task has a unique ID if the LLM forgot (it happens).
        # Also ensure status is BACKLOG.
        final_tasks = []
        for t in plan_obj.tasks:
            # We trust the LLM's title/desc, but we enforce system fields.
            t.id = t.id or str(uuid.uuid4())
            # Force status to backlog regardless of what LLM hallucinated
            final_tasks.append(t)
            
        return final_tasks