from typing import Any

from enterpriseagents.agents.builder import BuilderOutput
from enterpriseagents.agents.director import Plan
from enterpriseagents.agents.docs import DocsOutput
from enterpriseagents.core.models import AcceptanceCriteria, Task, ToolCall
from enterpriseagents.core.router import NextAction, RoutingDecision
from enterpriseagents.llm.provider import LlmProvider


class LocalScaffoldProvider(LlmProvider):
    """A deterministic scaffold provider for Sprint 1 local runs.
    
    Bypasses the need for paid LLM APIs while verifying the orchestration layer.
    """
    
    def __init__(self) -> None:
        self._router_calls = 0

    def completion(self, messages: list[dict[str, str]], model: str | None = None) -> str:
        return "Deterministic local completion"

    def structured(self, messages: list[dict[str, str]], schema: type[Any], model: str | None = None) -> Any:
        
        if schema == Plan:
            return Plan(tasks=[
                Task(
                    id="t1", 
                    title="Scaffold App", 
                    description="Create Python CLI and tests", 
                    acceptance=AcceptanceCriteria(checks=["python3 test_app.py", "python3 app.py"])
                ),
            ])
            
        if schema == BuilderOutput:
            return BuilderOutput(calls=[
                ToolCall(
                    tool_name="write_file", 
                    args={
                        "path": "app.py", 
                        "content": "def main():\n    print('Hello Enterprise')\n\nif __name__ == '__main__':\n    main()"
                    }, 
                    call_id="c1"
                ),
                ToolCall(
                    tool_name="write_file", 
                    args={
                        "path": "test_app.py", 
                        "content": "def test_main():\n    assert True"
                    }, 
                    call_id="c2"
                )
            ])
            
        if schema == DocsOutput:
            return DocsOutput(content="# Enterprise App\n\nGenerated by Local Scaffold.")
            
        if schema == RoutingDecision:
            self._router_calls += 1
            if self._router_calls == 1:
                return RoutingDecision(action=NextAction.WORK, reason="Let's build the app")
            if self._router_calls == 2:
                return RoutingDecision(action=NextAction.REVIEW, reason="Let's review the app")
            return RoutingDecision(action=NextAction.FINISH, reason="Done")
            
        raise ValueError(f"LocalScaffoldProvider doesn't know how to mock {schema}")
